--- #tasks to add a new user and grant ssh access to the user
- name: Add new user
  user:
    name: "{{ user_name }}"
    comment: "{{ user_des }}"
    shell: /bin/bash
  tags:
    - add

- name: Grant user SSH access
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', '../../../keys/{{ user_name }}/id_rsa.pub') }}"
  tags:
    - grant